# Generated by Django 5.0.4 on 2024-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.IntegerField(choices=[(1, 'Первый курс'), (2, 'Второй курс'), (3, 'Третий курс'), (4, 'Четвертый курс'), (5, 'Пятый курс')], default=5, verbose_name='Курс'),
        ),
    ]
