# Generated by Django 5.0.4 on 2024-05-09 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepody', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepod',
            options={'verbose_name': 'Препод', 'verbose_name_plural': 'Преподы'},
        ),
        migrations.AddField(
            model_name='prepod',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='prepody.category', verbose_name='Категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prepod',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кликуха'),
        ),
    ]
