# Generated by Django 5.0.4 on 2024-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepody', '0002_alter_prepod_options_prepod_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepod',
            options={'ordering': ['-time_create'], 'verbose_name': 'Препод', 'verbose_name_plural': 'Преподы'},
        ),
        migrations.AddField(
            model_name='prepod',
            name='phrases',
            field=models.CharField(default=1, max_length=255, verbose_name='Крутые фразы(через зарятую)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepod',
            name='post',
            field=models.CharField(choices=[('Professor', 'Профессор'), ('Docent', 'Доцент'), ('Old teacher', 'Старший преподаватель'), ('Assistant', 'Ассистент'), ('Old scientist worker', 'Старший научный сотрудник'), ('Lead engineer', 'Ведущий инженер')], default='Professor', max_length=20, verbose_name='Звание'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='prepod',
            index=models.Index(fields=['time_create'], name='prepody_pre_time_cr_5c6e52_idx'),
        ),
    ]
