# Generated by Django 5.0.4 on 2024-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepody', '0003_alter_prepod_options_prepod_phrases_prepod_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='post',
            field=models.CharField(choices=[('Профессор', 'Профессор'), ('Доцент', 'Доцент'), ('Старший преподаватель', 'Старший преподаватель'), ('Ассистент', 'Ассистент'), ('Старший научный сотрудник', 'Старший научный сотрудник'), ('Ведущий инженер', 'Ведущий инженер')], max_length=40, verbose_name='Звание'),
        ),
    ]
